#!/usr/bin/env bash
set -euo pipefail
source .config

usage() {
    cat <<EOF
Usage: ./post content of post

Options:
  -v / --visibility: set the post's visibility - public/unlisted/private/direct
EOF
}

if [ $# -eq 0 ];
then
    usage
    exit 1
fi

VISIBILITY=$DEFAULT_VISIBILITY
IMAGES=()
IMGLEN=0
POSITIONAL=($(read -t 1 || echo ""))

while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    -v|--visibility)
    VISIBILITY="$2"
    shift # past argument
    shift # past value
    ;;
    -i|--image)
    IMAGES[$IMGLEN]="$2"
    IMGLEN=$(($IMGLEN+1))
    shift
    shift
    ;;
    -h|--help)
    usage
    exit 0
    ;;
    *)    # unknown option
    POSITIONAL+=("$1") # save it in an array for later
    shift # past argument
    ;;
esac
done

MSG=${POSITIONAL[@]}
MEDIAIDS=()
IMGLEN=0

POST_COMMAND="
curl --silent \
    -XPOST $INSTANCE_URL/api/v1/statuses 
    --header \"Authorization: $ACCESS_TOKEN\" 
    --data-urlencode \"status=$MSG\" 
    --data-urlencode \"visibility=$VISIBILITY\"
"

for i in ${IMAGES[@]}; do
  echo "UPLOAD $i"
  RESP=$(curl --silent \
    -XPOST \
    $INSTANCE_URL/api/v1/media \
    --header "Authorization: $ACCESS_TOKEN" \
    -F "file=@$i")
  ID=$(echo $RESP | jq .id | sed "s|\"||g")
  POST_COMMAND+=" --data-urlencode \"media_ids[]=$ID\""
done

RESP=$(eval $POST_COMMAND)
echo $(echo $RESP | jq .url)
